### ISSUE TITLE
Hidden Multiplication

### ISSUE THREAD

**Issue by mcreng** [danvim/ProcalParsing#8]
### Codes
`$a$b$c`

### Error Returned
`org.bychan.core.basic.ParsingFailedException: Parsing failed: 'Current token does not support led parsing' @  position 1:6 (index 5), current lexeme is variable($c), previous was variable($b), and remaining are [colon(:), END]
        at org.bychan.core.basic.ParseResult.checkSuccess(ParseResult.java:83)
        at org.bychan.core.basic.ParseResult.getRootNode(ParseResult.java:36)
        at fx50.Main$Run.run(Main.java:120)
        at fx50.Main.main(Main.java:29)
Error: Parsing failed: 'Current token does not support led parsing' @  position 1:6 (index 5), current lexeme is variable($c), previous was variable($b), and remaining are [colon(:), END]`

**Comment by danvim** [comment]
Should be fixed in commit 0822044

**Comment by danvim** [comment]
Should be fixed in commit 0822044
